{% set name = "azure-servicebus" %}

package:
  name: "{{ name|lower }}"
  version: {{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}

source:
  url: {{ environ.get('SERVICEBUS_SOURCE_DISTRIBUTION', '') }}

build:
  script_env:
    - SERVICEBUS_SOURCE_DISTRIBUTION
    - SERVICEBUS_SUMMARY
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - azure-core >=2021.06.01
    - isodate
    - msrest >=2021.06.01
    - pip
    - python
    - requests-oauthlib >=0.5.0
    - six >=1.11.0
    - uamqp >=2021.06.01
    - aiohttp
  run:
    - azure-core >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - isodate
    - msrest >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - python
    - requests-oauthlib >=0.5.0
    - six >=1.11.0
    - uamqp >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - aiohttp

test:
  imports:
    - azure.servicebus
    - azure.servicebus._common
    - azure.servicebus.aio
    - azure.servicebus.aio.management
    - azure.servicebus.management

about:
  home: "https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/servicebus/azure-servicebus"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Microsoft Azure Service Bus Client Library for Python{{ environ.get('SERVICEBUS_SUMMARY', '') }}"
  description: |
    Azure Service Bus is a high performance cloud-managed messaging service for providing real-time and fault-tolerant communication between distributed senders and receivers.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - xiangyan99
