{% set name = "azure-ai-textanalytics" %}

package:
  name: "{{ name|lower }}"
  version: {{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}

source:
  url: {{ environ.get('TEXTANALYTICS_SOURCE_DISTRIBUTION', '') }}

build:
  script_env:
    - TEXTANALYTICS_SOURCE_DISTRIBUTION
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - azure-core >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - azure-identity >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - msrest >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - pip
    - python
    - six
    - requests-oauthlib >=0.5.0
    - aiohttp
  run:
    - azure-core >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - azure-identity >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - msrest >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - python
    - six
    - requests-oauthlib >=0.5.0
    - aiohttp

test:
  imports:
    - azure.ai.textanalytics
    - azure.ai.textanalytics.aio

about:
  home: "https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/textanalytics/azure-ai-textanalytics"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Microsoft Azure Text Analytics Client Library for Python{{ environ.get('TEXTANALYTICS_SUMMARY', '') }}"
  description: |
    Text Analytics is a cloud-based service that provides advanced natural language processing over raw text.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - xiangyan99
