trigger: none

extends:
  template: ../../eng/pipelines/templates/stages/archetype-conda-client.yml
  parameters:
    CondaArtifacts:
    - name: azure-core
      meta_source: conda-recipe/meta.yaml
      common_root: azure
      service: storage
      checkout:
        - package: azure-core
          checkout_path: sdk/core
          version: 1.12.0
    - name: azure-storage
      meta_source: conda-recipe/meta.yaml
      common_root: azure/storage
      service: storage
      checkout:
        - package: azure-storage-blob
          checkout_path: sdk/storage
          version: 12.8.0
        - package: azure-storage-queue
          checkout_path: sdk/storage
          version: 12.1.5
        - package: azure-storage-file-share
          checkout_path: sdk/storage
          version: 12.4.1
        - package: azure-storage-file-datalake
          checkout_path: sdk/storage
          version: 12.3.0
