trigger: none

extends:
  template: ../../eng/pipelines/templates/stages/archetype-conda-client.yml
  parameters:
    CondaArtifacts:
    - name: azure-core
      meta_source: conda-recipe/meta.yaml
      common_root: azure
      service: core
      checkout:
        - package: azure-core
          checkout_path: sdk/core
          version: 1.12.0
    - name: azure-identity
      meta_source: conda-recipe/meta.yaml
      common_root: azure
      service: core
      checkout:
        - package: azure-identity
          checkout_path: sdk/identity
          version: 1.6.0
    - name: azure-storage
      meta_source: conda-recipe/meta.yaml
      common_root: azure/storage
      service: storage
      checkout:
        - package: azure-storage-blob
          checkout_path: sdk/storage
          version: 12.8.0
        - package: azure-storage-queue
          checkout_path: sdk/storage
          version: 12.1.5
        - package: azure-storage-file-share
          checkout_path: sdk/storage
          version: 12.4.1
        - package: azure-storage-file-datalake
          checkout_path: sdk/storage
          version: 12.3.0
    - name: azure-ai-textanalytics
      meta_source: conda-recipe/meta.yaml
      common_root: azure
      service: textanalytics
      checkout:
        - package: azure-ai-textanalytics
          checkout_path: sdk/textanalytics
          version: 5.0.0
    - name: azure-appconfiguration
      meta_source: conda-recipe/meta.yaml
      common_root: azure
      service: appconfiguration
      checkout:
        - package: azure-appconfiguration
          checkout_path: sdk/appconfiguration
          version: 1.1.1
    - name: azure-communication
      meta_source: conda-recipe/meta.yaml
      common_root: azure/communication
      service: communication
      checkout:
        - package: azure-communication-chat
          checkout_path: sdk/communication
          version: 1.0.0
        - package: azure-communication-identity
          checkout_path: sdk/communication
          version: 1.0.0
        - package: azure-communication-phonenumbers
          checkout_path: sdk/communication
          version: 1.0.0
        - package: azure-communication-sms
          checkout_path: sdk/communication
          version: 1.0.0
    - name: azure-search-documents
      meta_source: conda-recipe/meta.yaml
      common_root: azure
      service: search
      checkout:
        - package: azure-search-documents
          checkout_path: sdk/search
          version: 11.1.0
