parameters:
  - name: CondaArtifacts
    type: object
    default: []
  - name: TestMarkArgument
    type: string
    default: ''
  - name: TestTimeoutInMinutes
    type: number
    default: 0
  - name: MatrixConfigs
    type: object
  - name: MatrixFilters
    type: object
    default: []
  - name: MatrixReplace
    type: object
    default: []

jobs:
  - job: 'Build'
    timeoutInMinutes: 90
    variables:
    - template: ../variables/globals.yml

    pool:
      name: azsdk-pool-mms-ubuntu-1804-general
      vmImage: MMSUbuntu18.04

    steps:
    - template: ../steps/build-conda-artifacts.yml
      parameters:
        CondaArtifacts: ${{ parameters.CondaArtifacts }}

  - template: /eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
    parameters:
      JobTemplatePath: /eng/pipelines/templates/jobs/ci.conda.tests.yml
      GenerateJobName: generate_conda_matrix
      DependsOn:
        - 'Build'
      MatrixConfigs:
          - Name: Python_ci_conda_envs
            Path: eng/pipelines/templates/stages/platform-matrix-conda-support.json
            Selection: sparse
            GenerateVMJobs: true
      MatrixFilters: ${{ parameters.MatrixFilters }}
      MatrixReplace: ${{ parameters.MatrixReplace }}
      CloudConfig:
        Cloud: Public
      AdditionalParameters:
        TestMarkArgument: ${{ parameters.TestMarkArgument }}
        TestTimeoutInMinutes: ${{ parameters.TestTimeoutInMinutes }}
        CondaArtifacts: ${{ parameters.CondaArtifacts}}