trigger:
  - master

jobs:

  - job: Validate_Nightly_Python_Build
    variables:
      skipComponentGovernanceDetection: true

    timeoutInMinutes: 90

    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python 3.7 For Build Tools'
        inputs:
          versionSpec: '3.7'

      - pwsh: |
          $installerFolder = "$(Build.SourcesDirectory)/../py39installer"
          Write-Host "Starting Install to $installerFolder"

          mkdir $installerFolder
          Invoke-WebRequest -Method GET `
            -Uri https://github.com/actions/python-versions/releases/download/3.9.0-rc.2-82072/python-3.9.0-rc.2-linux-18.04-x64.tar.gz `
            -OutFile $installerFolder/local.tar.gz

          cd $installerFolder

          Get-ChildItem -R -Force -Path $installerFolder 

          tar -xvf "$installerFolder/local.tar.gz"
        displayName: 'Install Py39-rc2'
        continueOnError: true

      - script: |
          sh ./setup.sh

          echo $PATH
        displayName: 'Install Py39 from script to avoid error?'
        workingDirectory: $(Build.SourcesDirectory)/../py39installer
        continueOnError: true

      - task: UsePythonVersion@0
        displayName: 'Use Python 3.9 For Build Tools'
        inputs:
          versionSpec: '3.9.0-rc.2'

      - script: |
          python --version

          pip install setuptools wheel 
          pip install tox tox-monorepo packaging twine codecov beautifulsoup4

          python ./scripts/devops_tasks/setup_execute_tests.py "$(BuildTargetingString)" --junitxml="junit/test_results_38.xml" --toxenv="whl,sdist"
        displayName: 'Setup - Run Filtered Tests "Nightly" using Python Edge'
        continueOnError: true

      - task: PublishTestResults@2
        condition: always()
        inputs:
          testResultsFiles: '**/junit/test-results.xml'
          testRunTitle: '$(OSName) Python $(PythonVersion)'
          failTaskOnFailedTests: true
