apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: '{{ .Release.Name }}-{{ .Release.Revision }}'
  namespace: {{ .Release.Namespace }}
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
  labels:
    scenario: 'stress'
    release: '{{ .Release.Name }}'
    revision: '{{ .Release.Revision }}'
spec:
  schedule: '@every 30s'
  type: 'NetworkChaos'
  networkChaos:
    action: loss
    mode: one
    selector:
      labelSelectors:
        testInstance: "servicebus-{{ .Release.Name }}-{{ .Release.Revision }}"
        chaos: 'true'
      namespaces:
        - {{ .Release.Namespace }}
      podPhaseSelectors:
        - 'Running'
    duration: '10s'
    direction: to
    externalTargets:
      - 'servicebus.windows.net'
    loss:
      loss: '100'
      correlation: '100'
