{% set name = "azure-keyvault" %}

package:
  name: "{{ name|lower }}"
  version: {{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}

source:
  url: {{ environ.get('KEYVAULT_SOURCE_DISTRIBUTION', '') }}

build:
  script_env:
    - KEYVAULT_SOURCE_DISTRIBUTION
    - KEYVAULT_SUMMARY
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - azure-core >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - azure-identity >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - cryptography
    - msrest >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - pip
    - python
    - requests-oauthlib >=0.5.0
    - aiohttp
  run:
    - azure-core >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - azure-identity >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - cryptography
    - msrest >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - python
    - requests-oauthlib >=0.5.0
    - aiohttp

test:
  imports:
    - azure.keyvault.keys
    - azure.keyvault.certificates
    - azure.keyvault.secrets

about:
  home: "https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Microsoft Azure Key Vault Keys Client Library for Python{{ environ.get('KEYVAULT_SUMMARY', '') }}"
  description: |
    This is the Microsoft Azure Key Vault libraries bundle.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - xiangyan99
