{% set name = "azure-communication" %}

package:
  name: "{{ name|lower }}"
  version: {{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}

source:
  url: {{ environ.get('COMMUNICATION_SOURCE_DISTRIBUTION', '') }}

build:
  script_env:
    - COMMUNICATION_SOURCE_DISTRIBUTION
    - COMMUNICATION_SUMMARY
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - azure-core >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - azure-identity >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - msrest >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - pip
    - python
    - six
    - aiohttp
  run:
    - azure-core >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - azure-identity >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - msrest >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - python
    - six
    - aiohttp

test:
  imports:
    - azure.communication.chat
    - azure.communication.chat.aio
    - azure.communication.identity
    - azure.communication.identity.aio
    - azure.communication.phonenumbers
    - azure.communication.phonenumbers.aio
    - azure.communication.sms
    - azure.communication.sms.aio

about:
  home: "https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Azure Communication Package client library for Python{{ environ.get('COMMUNICATION_SUMMARY', '') }}"
  description: |
    This is the Microsoft Azure Communication libraries bundle.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - xiangyan99
