parameters:
- name: CondaArtifacts
  type: object
  default: []
- name: TestTimeoutInMinutes
  type: number
  default: 0
- name: DevFeedName
  type: string
  default: public/azure-sdk-for-python
- name: MatrixConfigs
  type: object
  default:
    - Name: Python_ci_test_base
      Path: eng/pipelines/templates/stages/platform-matrix.json
      Selection: sparse
      GenerateVMJobs: true
- name: AdditionalMatrixConfigs
  type: object
  default: []
- name: MatrixFilters
  type: object
  default: []
- name: MatrixReplace
  type: object
  default: []

stages:
  - stage: Build
    jobs:
    - template: /eng/pipelines/templates/jobs/ci.conda.yml
      parameters:
        CondaArtifacts: ${{ parameters.CondaArtifacts }}
        TestMarkArgument: not cosmosEmulator
        TestTimeoutInMinutes: ${{ parameters.TestTimeoutInMinutes }}
        MatrixConfigs:
          - ${{ each config in parameters.MatrixConfigs }}:
            -  ${{ config }}
          - ${{ each config in parameters.AdditionalMatrixConfigs }}:
            -  ${{ config }}
        MatrixFilters: ${{ parameters.MatrixFilters }}
        MatrixReplace: ${{ parameters.MatrixReplace }}

  # The Prerelease and Release stages are conditioned on whether we are building a pull request and the branch.
  - ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal'))}}:
    - template: archetype-conda-release.yml
      parameters:
        DependsOn: Build
        ServiceDirectory: ${{ parameters.ServiceDirectory }}
        CondaArtifacts: ${{ parameters.CondaArtifacts }}
        ArtifactName: conda
        ${{ if eq(parameters.ServiceDirectory, 'template') }}:
          TestPipeline: true

